### ISSUE TITLE
Feature request: same random color for each tab with same domain

### ISSUE THREAD

**Issue by MurzNN** [meph1570/treestyletab#1]
In Colorfultabs there are very useful mode when each tab from same domain have same random color, eg google.com have green color, wikipedia.org - yellow, etc.

Will be good to have this mode in your extension too!

**Comment by meph1570** [comment]
Should be working as expected in today's update. Check `Enable hostname colors` and `Determine tab colors based on hostname` in the addon's settings.

**Comment by MurzNN** [comment]
Thanks, now works well!
