### ISSUE TITLE
Convert TST RainbowTabsFork to separate addon, that use TST addon API

### ISSUE THREAD

**Issue by MurzNN** [meph1570/treestyletab#6]
At now TST RainbowTabsFork stays as fork of original Tree Style Tabs extension, with adding ability to colorize tabs background, based on domain.

TST original extension is very often updated, and those updates are not automatically backported to Tree Style Tab RainbowTabsFork project, so this make support of this fork too hard.

Also Tree Style Tab RainbowTabsFork have no support for [other TST addons](https://github.com/meph1570/treestyletab#user-content-addons-extend-tst) (https://github.com/meph1570/treestyletab/issues/5).

TST developer describe [here](https://github.com/piroor/treestyletab/issues/1645#issuecomment-393222099) the way how we can colorize tabs via separate extension, that use TST addons.

Can you convert your fork to separate extension, that implement same tab colorize functional via TST addons API?

**Comment by infinity0** [comment]
+1 please consider doing this, this extension is way out of date compared to normal TST now

**Comment by MurzNN** [comment]
I created new separate extension that implement colored tabs, based on domain: https://addons.mozilla.org/firefox/addon/tst-colored-tabs/
